package superime.prodajavozila;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dojmovi implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("DojmoviID")
   private java.lang.Long dojmovi_id;
   @org.kie.api.definition.type.Label("Dojam")
   private java.lang.String dojam;

   @org.kie.api.definition.type.Label(value = "PonudaID")
   private superime.prodajavozila.Ponuda ponudaID;

   public Dojmovi()
   {
   }

   public java.lang.Long getDojmovi_id()
   {
      return this.dojmovi_id;
   }

   public void setDojmovi_id(java.lang.Long dojmovi_id)
   {
      this.dojmovi_id = dojmovi_id;
   }

   public java.lang.String getDojam()
   {
      return this.dojam;
   }

   public void setDojam(java.lang.String dojam)
   {
      this.dojam = dojam;
   }

   public superime.prodajavozila.Ponuda getPonudaID()
   {
      return this.ponudaID;
   }

   public void setPonudaID(superime.prodajavozila.Ponuda ponudaID)
   {
      this.ponudaID = ponudaID;
   }

   public Dojmovi(java.lang.Long dojmovi_id, java.lang.String dojam,
         superime.prodajavozila.Ponuda ponudaID)
   {
      this.dojmovi_id = dojmovi_id;
      this.dojam = dojam;
      this.ponudaID = ponudaID;
   }

}