package superime.prodajavozila;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dojmovi implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Dojmovi() {
    }

}