package superime.prodajavozila;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dojmovi implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "DojmoviID")
   private java.lang.Long dojmovi_id;
   @org.kie.api.definition.type.Label(value = "KupacID")
   private java.lang.Long kupac_id;
   @org.kie.api.definition.type.Label(value = "Dojam")
   private java.lang.String dojam;

   public Dojmovi()
   {
   }

   public java.lang.Long getDojmovi_id()
   {
      return this.dojmovi_id;
   }

   public void setDojmovi_id(java.lang.Long dojmovi_id)
   {
      this.dojmovi_id = dojmovi_id;
   }

   public java.lang.Long getKupac_id()
   {
      return this.kupac_id;
   }

   public void setKupac_id(java.lang.Long kupac_id)
   {
      this.kupac_id = kupac_id;
   }

   public java.lang.String getDojam()
   {
      return this.dojam;
   }

   public void setDojam(java.lang.String dojam)
   {
      this.dojam = dojam;
   }

   public Dojmovi(java.lang.Long dojmovi_id, java.lang.Long kupac_id,
         java.lang.String dojam)
   {
      this.dojmovi_id = dojmovi_id;
      this.kupac_id = kupac_id;
      this.dojam = dojam;
   }

}