package superime.prodajavozila;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Kupac")
public class Kupac implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public Kupac()
   {
   }

}