package superime.prodajavozila;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Narudzba implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Narudzba ID")
   private java.lang.Long narudzba_id;
   @org.kie.api.definition.type.Label("Napomena")
   private java.lang.String napomena;

   public Narudzba()
   {
   }

   public java.lang.Long getNarudzba_id()
   {
      return this.narudzba_id;
   }

   public void setNarudzba_id(java.lang.Long narudzba_id)
   {
      this.narudzba_id = narudzba_id;
   }

   public java.lang.String getNapomena()
   {
      return this.napomena;
   }

   public void setNapomena(java.lang.String napomena)
   {
      this.napomena = napomena;
   }

   public Narudzba(java.lang.Long narudzba_id, java.lang.String napomena)
   {
      this.narudzba_id = narudzba_id;
      this.napomena = napomena;
   }

}