package superime.prodajavozila;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PonovniKontakt implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Ponovni kontakt ID")
   private java.lang.Long ponovni_kontaktID;
   @org.kie.api.definition.type.Label("KupacID")
   private Kupac kupac_id;
   @org.kie.api.definition.type.Label("Izvjestaj prije narudzbe")
   private java.lang.String izvjestaj_prije;
   @org.kie.api.definition.type.Label("Izvjestaj poslije narudzbe")
   private java.lang.String izvjestaj_poslije;

   public PonovniKontakt()
   {
   }

   public java.lang.Long getPonovni_kontaktID()
   {
      return this.ponovni_kontaktID;
   }

   public void setPonovni_kontaktID(java.lang.Long ponovni_kontaktID)
   {
      this.ponovni_kontaktID = ponovni_kontaktID;
   }

   public java.lang.String getIzvjestaj_prije()
   {
      return this.izvjestaj_prije;
   }

   public void setIzvjestaj_prije(java.lang.String izvjestaj_prije)
   {
      this.izvjestaj_prije = izvjestaj_prije;
   }

   public java.lang.String getIzvjestaj_poslije()
   {
      return this.izvjestaj_poslije;
   }

   public void setIzvjestaj_poslije(java.lang.String izvjestaj_poslije)
   {
      this.izvjestaj_poslije = izvjestaj_poslije;
   }

   public superime.prodajavozila.Kupac getKupac_id()
   {
      return this.kupac_id;
   }

   public void setKupac_id(superime.prodajavozila.Kupac kupac_id)
   {
      this.kupac_id = kupac_id;
   }

   public PonovniKontakt(java.lang.Long ponovni_kontaktID,
         superime.prodajavozila.Kupac kupac_id,
         java.lang.String izvjestaj_prije, java.lang.String izvjestaj_poslije)
   {
      this.ponovni_kontaktID = ponovni_kontaktID;
      this.kupac_id = kupac_id;
      this.izvjestaj_prije = izvjestaj_prije;
      this.izvjestaj_poslije = izvjestaj_poslije;
   }

}