package superime.prodajavozila;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Ponuda")
public class Ponuda implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "PonudaID")
   private java.lang.Long ponudaID;
   @org.kie.api.definition.type.Label(value = "KupacID")
   private superime.prodajavozila.Kupac kupacID;

   public Ponuda()
   {
   }

   public java.lang.Long getPonudaID()
   {
      return this.ponudaID;
   }

   public void setPonudaID(java.lang.Long ponudaID)
   {
      this.ponudaID = ponudaID;
   }

   public superime.prodajavozila.Kupac getKupacID()
   {
      return this.kupacID;
   }

   public void setKupacID(superime.prodajavozila.Kupac kupacID)
   {
      this.kupacID = kupacID;
   }

   public Ponuda(java.lang.Long ponudaID, superime.prodajavozila.Kupac kupacID)
   {
      this.ponudaID = ponudaID;
      this.kupacID = kupacID;
   }

}