package superime.prodajavozila;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Vozilo")
public class Vozilo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "VoziloID")
   private java.lang.Long voziloID;
   @org.kie.api.definition.type.Label(value = "Vrsta")
   private java.lang.String vrsta;
   @org.kie.api.definition.type.Label(value = "Model")
   private java.lang.String model;

   public Vozilo()
   {
   }

   public java.lang.Long getVoziloID()
   {
      return this.voziloID;
   }

   public void setVoziloID(java.lang.Long voziloID)
   {
      this.voziloID = voziloID;
   }

   public java.lang.String getVrsta()
   {
      return this.vrsta;
   }

   public void setVrsta(java.lang.String vrsta)
   {
      this.vrsta = vrsta;
   }

   public java.lang.String getModel()
   {
      return this.model;
   }

   public void setModel(java.lang.String model)
   {
      this.model = model;
   }

   public Vozilo(java.lang.Long voziloID, java.lang.String vrsta,
         java.lang.String model)
   {
      this.voziloID = voziloID;
      this.vrsta = vrsta;
      this.model = model;
   }

}